CREATE TABLE [dbo].[USERS] (
    [Id]                   INT           IDENTITY (1, 1) NOT NULL,
    [EMAIL]                VARCHAR (250) CONSTRAINT [DEFAULT_USERS_EMAIL] DEFAULT '' NOT NULL,
    [PASSWORD]             VARCHAR (100) NOT NULL,
    [CREATED_AT]           DATETIME      CONSTRAINT [DEFAULT_USERS_CREATED_AT] DEFAULT GETDATE() NOT NULL,
    CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED ([Id] ASC, [EMAIL] ASC)
);

